name: Supabase Sign-In

on:
  workflow_dispatch:  # Allows manual execution


jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Sign In to Supabase
        run: |
          curl -X POST "https://abbrzfjcqgwkcsrvtnrm.supabase.co/auth/v1/token?grant_type=password" \
               -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
               -H "Content-Type: application/json" \
               -d '{
                     "email": "test@keepalive.com",
                     "password": "keepmyprojectalive"
                   }'
