name: Supabase Sign-In

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at 00:00 UTC
  workflow_dispatch:  # Allows manual execution


jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Sign In to Supabase
        run: |
          curl -X POST "https://abbrzfjcqgwkcsrvtnrm.supabase.co/auth/v1/token?grant_type=password" \
               -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYnJ6ZmpjcWd3a2NzcnZ0bnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODI4ODgsImV4cCI6MjA1NzA1ODg4OH0.h_xrA5Nc4Y4dO40v0BhVXK0n_t0CpGou_x3QmLL31U0" \
               -H "Content-Type: application/json" \
               -d '{
                     "email": "test@keepalive.com",
                     "password": "keepmyprojectalive"
                   }'
