name: Supabase Client Ping

on:
  schedule:
    - cron: "0 0 * * 1,4"  # Every Monday and Thursday at 00:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Supabase client
        run: npm install @supabase/supabase-js

      - name: Run Supabase ping
        env:
          SUPABASE_URL: https://abbrzfjcqgwkcsrvtnrm.supabase.co
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYnJ6ZmpjcWd3a2NzcnZ0bnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODI4ODgsImV4cCI6MjA1NzA1ODg4OH0.h_xrA5Nc4Y4dO40v0BhVXK0n_t0CpGou_x3QmLL31U0
        run: |
          node <<EOF
          import { createClient } from '@supabase/supabase-js'

          const supabase = createClient(
            process.env.SUPABASE_URL,
            process.env.SUPABASE_ANON_KEY
          );

          const ping = async () => {
            const { data, error } = await supabase
              .from('user_profiles')
              .select('id')
              .limit(1);

            if (error) {
              console.error("Ping failed:", error.message);
              process.exit(1);
            } else {
              console.log("Ping successful:", data);
            }
          };

          ping();
          EOF
